# Generated by Django 3.2.4 on 2021-06-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.CharField(max_length=255, verbose_name='Email ')),
                ('department', models.CharField(max_length=255, verbose_name='Department ')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=9, null=True, verbose_name='Salary')),
                ('birth_date', models.DateTimeField(verbose_name='Birth Data')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['name'],
            },
        ),
    ]
